FROM maven:3.8.7
WORKDIR /backend

# Copia el archivo pom.xml y descarga las dependencias
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia el código fuente
COPY src ./src
COPY .env .env

# Exponer el puerto 8080
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["mvn", "spring-boot:run","-Dspring-boot.run.profiles=dev"]